# simple prompt: user@host path [git] $
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$character"""

[username]
show_always = true
format = "[$user]($style)@"
style_user = "bold blue"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold blue"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = ""
format = "[$symbol$branch]($style)"
style = "green"

[git_status]
format = "$conflicted$stashed$staged$modified$untracked$ahead_behind "
conflicted = "[*](bold red)"
stashed = ""
staged = "[•](yellow)"
modified = "[•](yellow)"
renamed = "[•](yellow)"
deleted = "[•](yellow)"
untracked = "[•](green)"
ahead = "[↑](cyan)"
behind = "[↓](cyan)"
diverged = "[↕](cyan)"

[python]
format = "[${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
style = "yellow"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
